#pragma once

#include <stdbool.h>

#include <parser/rule.h>

enum {
    NT_PRIMARY_EXPRESSION,

    NT_POSTFIX_EXPRESSION,
    NT_ARGUMENT_EXPRESSION_LIST,

    NT_UNARY_EXPRESSION,
    NT_UNARY_OPERATOR,
    NT_CAST_EXPRESSION,

    NT_MULTIPLICATIVE_EXPRESSION,

    NT_ADDITIVE_EXPRESSION,

    NT_SHIFT_EXPRESSION,

    NT_RELATIONAL_EXPRESSION,

    NT_EQUALITY_EXPRESSION,

    NT_AND_EXPRESSION,
    NT_XOR_EXPRESSION,
    NT_OR_EXPRESSION,

    NT_LOGICAL_AND_EXPRESSION,
    NT_LOGICAL_OR_EXPRESSION,

    NT_CONDITIONAL_EXPRESSION,

    NT_ASSIGNMENT_EXPRESSION,
    NT_ASSIGNMENT_OPERATOR,

    NT_EXPRESSION,

    NT_CONSTANT_EXPRESSION,

    NT_DECLARATION,
    NT_DECLARATION_SPECIFIERS,

    NT_INIT_DECLARATOR_LIST,
    NT_INIT_DECLARATOR,

    NT_STORAGE_CLASS_SPECIFIER,

    NT_TYPE_SPECIFIER,

    NT_STRUCT_OR_UNION_SPECIFIER,
    NT_STRUCT_OR_UNION,
    NT_STRUCT_DECLARATION_LIST,
    NT_STRUCT_DECLARATION,
    NT_SPECIFIER_QUALIFIER_LIST,
    NT_STRUCT_DECLARATOR_LIST,
    NT_STRUCT_DECLARATOR,

    NT_ENUM_SPECIFIER,
    NT_ENUMERATOR_LIST,
    NT_ENUMERATOR,

    NT_TYPE_QUALIFIER,

    // FIX
    NT_FUNCTION_SPECIFIER,

    NT_DECLARATOR,
    NT_DIRECT_DECLARATOR,

    NT_POINTER,

    NT_TYPE_QUALIFIER_LIST,
    // END

    NT_PARAMETER_TYPE_LIST,
    NT_PARAMETER_LIST,
    NT_PARAMETER_DECLARATION,

    NT_IDENTIFIER_LIST,

    NT_TYPE_NAME,

    NT_ABSTRACT_DECLARATOR,
    NT_DIRECT_ABSTRACT_DECLARATOR,

    NT_INITIALIZER,
    NT_INITIALIZER_LIST,

    NT_DESIGNATION,
    NT_DESIGNATOR_LIST,
    NT_DESIGNATOR,

    NT_STATEMENT,

    NT_LABELED_STATEMENT,

    NT_COMPOUND_STATEMENT,

    NT_BLOCK_ITEM_LIST,
    NT_BLOCK_ITEM,

    NT_EXPRESSION_STATEMENT,

    NT_SELECTION_STATEMENT,
    NT_ITERATION_STATEMENT,
    NT_JUMP_STATEMENT,

    NT_TRANSLATION_UNIT,
    NT_EXTERNAL_DECLARATION,

    NT_FUNCTION_DEFINITION,

    NT_DECLARATION_LIST,

    NT_COUNT,

    NT_START,
    NT_NULL,
};

static inline const char * rules_nonterminal_name(nonterminal_t nonterminal) {
    switch (nonterminal) {
        case NT_PRIMARY_EXPRESSION: return "NT_PRIMARY_EXPRESSION";

        case NT_POSTFIX_EXPRESSION: return "NT_POSTFIX_EXPRESSION";
        case NT_ARGUMENT_EXPRESSION_LIST: return "NT_ARGUMENT_EXPRESSION_LIST";

        case NT_UNARY_EXPRESSION: return "NT_UNARY_EXPRESSION";
        case NT_UNARY_OPERATOR: return "NT_UNARY_OPERATOR";
        case NT_CAST_EXPRESSION: return "NT_CAST_EXPRESSION";

        case NT_MULTIPLICATIVE_EXPRESSION: return "NT_MULTIPLICATIVE_EXPRESSION";

        case NT_ADDITIVE_EXPRESSION: return "NT_ADDITIVE_EXPRESSION";

        case NT_SHIFT_EXPRESSION: return "NT_SHIFT_EXPRESSION";

        case NT_RELATIONAL_EXPRESSION: return "NT_RELATIONAL_EXPRESSION";

        case NT_EQUALITY_EXPRESSION: return "NT_EQUALITY_EXPRESSION";

        case NT_AND_EXPRESSION: return "NT_AND_EXPRESSION";
        case NT_XOR_EXPRESSION: return "NT_XOR_EXPRESSION";
        case NT_OR_EXPRESSION: return "NT_OR_EXPRESSION";

        case NT_LOGICAL_AND_EXPRESSION: return "NT_LOGICAL_AND_EXPRESSION";
        case NT_LOGICAL_OR_EXPRESSION: return "NT_LOGICAL_OR_EXPRESSION";

        case NT_CONDITIONAL_EXPRESSION: return "NT_CONDITIONAL_EXPRESSION";

        case NT_ASSIGNMENT_EXPRESSION: return "NT_ASSIGNMENT_EXPRESSION";
        case NT_ASSIGNMENT_OPERATOR: return "NT_ASSIGNMENT_OPERATOR";

        case NT_EXPRESSION: return "NT_EXPRESSION";

        case NT_CONSTANT_EXPRESSION: return "NT_CONSTANT_EXPRESSION";

        case NT_DECLARATION: return "NT_DECLARATION";
        case NT_DECLARATION_SPECIFIERS: return "NT_DECLARATION_SPECIFIERS";

        case NT_INIT_DECLARATOR_LIST: return "NT_INIT_DECLARATOR_LIST";
        case NT_INIT_DECLARATOR: return "NT_INIT_DECLARATOR";

        case NT_STORAGE_CLASS_SPECIFIER: return "NT_STORAGE_CLASS_SPECIFIER";

        case NT_TYPE_SPECIFIER: return "NT_TYPE_SPECIFIER";

        case NT_STRUCT_OR_UNION_SPECIFIER: return "NT_STRUCT_OR_UNION_SPECIFIER";
        case NT_STRUCT_OR_UNION: return "NT_STRUCT_OR_UNION";
        case NT_STRUCT_DECLARATION_LIST: return "NT_STRUCT_DECLARATION_LIST";
        case NT_STRUCT_DECLARATION: return "NT_STRUCT_DECLARATION";
        case NT_SPECIFIER_QUALIFIER_LIST: return "NT_SPECIFIER_QUALIFIER_LIST";
        case NT_STRUCT_DECLARATOR_LIST: return "NT_STRUCT_DECLARATOR_LIST";
        case NT_STRUCT_DECLARATOR: return "NT_STRUCT_DECLARATOR";

        case NT_ENUM_SPECIFIER: return "NT_ENUM_SPECIFIER";
        case NT_ENUMERATOR_LIST: return "NT_ENUMERATOR_LIST";
        case NT_ENUMERATOR: return "NT_ENUMERATOR";

        case NT_TYPE_QUALIFIER: return "NT_TYPE_QUALIFIER";

    // FIX
        case NT_FUNCTION_SPECIFIER: return "NT_FUNCTION_SPECIFIER";

        case NT_DECLARATOR: return "NT_DECLARATOR";
        case NT_DIRECT_DECLARATOR: return "NT_DIRECT_DECLARATOR";

        case NT_POINTER: return "NT_POINTER";

        case NT_TYPE_QUALIFIER_LIST: return "NT_TYPE_QUALIFIER_LIST";
    // END

        case NT_PARAMETER_TYPE_LIST: return "NT_PARAMETER_TYPE_LIST";
        case NT_PARAMETER_LIST: return "NT_PARAMETER_LIST";
        case NT_PARAMETER_DECLARATION: return "NT_PARAMETER_DECLARATION";

        case NT_IDENTIFIER_LIST: return "NT_IDENTIFIER_LIST";

        case NT_TYPE_NAME: return "NT_TYPE_NAME";

        case NT_ABSTRACT_DECLARATOR: return "NT_ABSTRACT_DECLARATOR";
        case NT_DIRECT_ABSTRACT_DECLARATOR: return "NT_DIRECT_ABSTRACT_DECLARATOR";

        case NT_INITIALIZER: return "NT_INITIALIZER";
        case NT_INITIALIZER_LIST: return "NT_INITIALIZER_LIST";

        case NT_DESIGNATION: return "NT_DESIGNATION";
        case NT_DESIGNATOR_LIST: return "NT_DESIGNATOR_LIST";
        case NT_DESIGNATOR: return "NT_DESIGNATOR";

        case NT_STATEMENT: return "NT_STATEMENT";

        case NT_LABELED_STATEMENT: return "NT_LABELED_STATEMENT";

        case NT_COMPOUND_STATEMENT: return "NT_COMPOUND_STATEMENT";

        case NT_BLOCK_ITEM_LIST: return "NT_BLOCK_ITEM_LIST";
        case NT_BLOCK_ITEM: return "NT_BLOCK_ITEM";

        case NT_EXPRESSION_STATEMENT: return "NT_EXPRESSION_STATEMENT";

        case NT_SELECTION_STATEMENT: return "NT_SELECTION_STATEMENT";
        case NT_ITERATION_STATEMENT: return "NT_ITERATION_STATEMENT";
        case NT_JUMP_STATEMENT: return "NT_JUMP_STATEMENT";

        case NT_TRANSLATION_UNIT: return "NT_TRANSLATION_UNIT";
        case NT_EXTERNAL_DECLARATION: return "NT_EXTERNAL_DECLARATION";

        case NT_FUNCTION_DEFINITION: return "NT_FUNCTION_DEFINITION";

        case NT_DECLARATION_LIST: return "NT_DECLARATION_LIST";

        case NT_COUNT: return "NT_COUNT";

        case NT_START: return "NT_START";
        case NT_NULL: return "NT_NULL";

        default: return "UNKNOWN";
    }
}

static inline const char * rules_nonterminal_report_name(nonterminal_t nonterminal) {
    switch (nonterminal) {
        case NT_TRANSLATION_UNIT: return "translation unit";

        default: return "UNKNOWN";
    }
}
