#pragma once

#include <stdbool.h>

#include <parser/rule.h>

enum {
    NT_TRANSLATION_UNIT,
    NT_EXTERNAL_DECLARATION,

    NT_PRIMARY_EXPRESSION,

    NT_POSTFIX_EXPRESSION,
    NT_ARGUMENT_EXPRESSION_LIST,

    NT_UNARY_EXPRESSION,
    NT_UNARY_OPERATOR,
    NT_CAST_EXPRESSION,

    NT_MULTIPLICATIVE_EXPRESSION,

    NT_ADDITIVE_EXPRESSION,

    NT_SHIFT_EXPRESSION,

    NT_RELATIONAL_EXPRESSION,

    NT_EQUALITY_EXPRESSION,

    NT_AND_EXPRESSION,
    NT_XOR_EXPRESSION,
    NT_OR_EXPRESSION,

    NT_LOGICAL_AND_EXPRESSION,
    NT_LOGICAL_OR_EXPRESSION,

    NT_CONDITIONAL_EXPRESSION,

    NT_ASSIGNMENT_EXPRESSION,
    NT_ASSIGNMENT_OPERATOR,

    NT_EXPRESSION,

    NT_CONSTANT_EXPRESSION,

    NT_DECLARATION,
    NT_DECLARATION_SPECIFIERS,

    NT_INIT_DECLARATOR_LIST,
    NT_INIT_DECLARATOR,

    NT_STORAGE_CLASS_SPECIFIER,

    NT_TYPE_SPECIFIER,

    NT_STRUCT_OR_UNION_SPECIFIER,
    NT_STRUCT_OR_UNION,
    NT_STRUCT_DECLARATION_LIST,
    NT_STRUCT_DECLARATION,
    NT_SPECIFIER_QUALIFIER_LIST,
    NT_STRUCT_DECLARATOR_LIST,
    NT_STRUCT_DECLARATOR,

    NT_ENUM_SPECIFIER,
    NT_ENUMERATOR_LIST,
    NT_ENUMERATOR,

    NT_TYPE_QUALIFIER,

    NT_DECLARATOR,
    NT_INITIALIZER,
    NT_FUNCTION_SPECIFIER,
    NT_TYPE_NAME,
    NT_INITIALIZER_LIST,

    NT_NULL,
};

static inline const char * rules_nonterminal_name(nonterminal_t nonterminal) {
    switch (nonterminal) {
        case NT_TRANSLATION_UNIT: return "NT_TRANSLATION_UNIT";

        default: return "UNKNOWN";
    }
}

static inline const char * rules_nonterminal_report_name(nonterminal_t nonterminal) {
    switch (nonterminal) {
        case NT_TRANSLATION_UNIT: return "translation unit";

        default: return "UNKNOWN";
    }
}
