#include <string.h>
#include <stdio.h>

#include <scanner/token_stringify.h>

const char * keyword_strings[] = {
    [SCANNER_KEYWORD_TYPE_BREAK] = "BREAK",
    [SCANNER_KEYWORD_TYPE_CASE] = "CASE",
    [SCANNER_KEYWORD_TYPE_CHAR] = "CHAR",
    [SCANNER_KEYWORD_TYPE_CONST] = "CONST",
    [SCANNER_KEYWORD_TYPE_CONTINUE] = "CONTINUE",
    [SCANNER_KEYWORD_TYPE_DEFAULT] = "DEFAULT",
    [SCANNER_KEYWORD_TYPE_DO] = "DO",
    [SCANNER_KEYWORD_TYPE_DOUBLE] = "DOUBLE",
    [SCANNER_KEYWORD_TYPE_ELSE] = "ELSE",
    [SCANNER_KEYWORD_TYPE_ENUM] = "ENUM",
    [SCANNER_KEYWORD_TYPE_EXTERN] = "EXTERN",
    [SCANNER_KEYWORD_TYPE_FLOAT] = "FLOAT",
    [SCANNER_KEYWORD_TYPE_FOR] = "FOR",
    [SCANNER_KEYWORD_TYPE_GOTO] = "GOTO",
    [SCANNER_KEYWORD_TYPE_IF] = "IF",
    [SCANNER_KEYWORD_TYPE_INLINE] = "INLINE",
    [SCANNER_KEYWORD_TYPE_INT] = "INT",
    [SCANNER_KEYWORD_TYPE_LONG] = "LONG",
    [SCANNER_KEYWORD_TYPE_REGISTER] = "REGISTER",
    [SCANNER_KEYWORD_TYPE_RESTRICT] = "RESTRICT",
    [SCANNER_KEYWORD_TYPE_RETURN] = "RETURN",
    [SCANNER_KEYWORD_TYPE_SHORT] = "SHORT",
    [SCANNER_KEYWORD_TYPE_SIGNED] = "SIGNED",
    [SCANNER_KEYWORD_TYPE_SIZEOF] = "SIZEOF",
    [SCANNER_KEYWORD_TYPE_STATIC] = "STATIC",
    [SCANNER_KEYWORD_TYPE_STRUCT] = "STRUCT",
    [SCANNER_KEYWORD_TYPE_SWITCH] = "SWITCH",
    [SCANNER_KEYWORD_TYPE_TYPEDEF] = "TYPEDEF",
    [SCANNER_KEYWORD_TYPE_UNION] = "UNION",
    [SCANNER_KEYWORD_TYPE_UNSIGNED] = "UNSIGNED",
    [SCANNER_KEYWORD_TYPE_VOID] = "VOID",
    [SCANNER_KEYWORD_TYPE_VOLATILE] = "VOLATILE",
    [SCANNER_KEYWORD_TYPE_WHILE] = "WHILE",
    [SCANNER_KEYWORD_TYPE_BOOL] = "BOOL",
    [SCANNER_KEYWORD_TYPE_COMPLEX] = "COMPLEX",
    [SCANNER_KEYWORD_TYPE_IMAGINARY] = "IMAGINARY",
};

const char * constant_strings[] = {
    [SCANNER_CONSTANT_TYPE_UC] = "UC",
    [SCANNER_CONSTANT_TYPE_US] = "US",
    [SCANNER_CONSTANT_TYPE_UI] = "UI",
    [SCANNER_CONSTANT_TYPE_UL] = "UL",
    [SCANNER_CONSTANT_TYPE_ULL] = "ULL",

    [SCANNER_CONSTANT_TYPE_SC] = "SC",
    [SCANNER_CONSTANT_TYPE_SS] = "SS",
    [SCANNER_CONSTANT_TYPE_SI] = "SI",
    [SCANNER_CONSTANT_TYPE_SL] = "SL",
    [SCANNER_CONSTANT_TYPE_SLL] = "SLL",

    [SCANNER_CONSTANT_TYPE_FLOAT] = "FLOAT",
    [SCANNER_CONSTANT_TYPE_DOUBLE] = "DOUBLE",
};

const char * punctuation_strings[] = {
    [SCANNER_PUNCTUATION_TYPE_PLUS] = "PLUS",
    [SCANNER_PUNCTUATION_TYPE_MINUS] = "MINUS",
    [SCANNER_PUNCTUATION_TYPE_STAR] = "STAR",
    [SCANNER_PUNCTUATION_TYPE_SLASH] = "SLASH",
    [SCANNER_PUNCTUATION_TYPE_PERCENT] = "PERCENT",
    [SCANNER_PUNCTUATION_TYPE_INCREMENT] = "INCREMENT",
    [SCANNER_PUNCTUATION_TYPE_DECREMENT] = "DECREMENT",

    [SCANNER_PUNCTUATION_TYPE_EQUAL_TO] = "EQUAL_TO",
    [SCANNER_PUNCTUATION_TYPE_NOT_EQUAL_TO] = "NOT_EQUAL_TO",
    [SCANNER_PUNCTUATION_TYPE_GREATER_THAN] = "GREATER_THAN",
    [SCANNER_PUNCTUATION_TYPE_LESS_THAN] = "LESS_THAN",
    [SCANNER_PUNCTUATION_TYPE_GREATER_THAN_OR_EQUAL_TO] = "GREATER_THAN_OR_EQUAL_TO",
    [SCANNER_PUNCTUATION_TYPE_LESS_THAN_OR_EQUAL_TO] = "LESS_THAN_OR_EQUAL_TO",

    [SCANNER_PUNCTUATION_TYPE_LOGICAL_NEGATION] = "LOGICAL_NEGATION",
    [SCANNER_PUNCTUATION_TYPE_LOGICAL_AND] = "LOGICAL_AND",
    [SCANNER_PUNCTUATION_TYPE_LOGICAL_OR] = "LOGICAL_OR",

    [SCANNER_PUNCTUATION_TYPE_BITWISE_NOT] = "BITWISE_NOT",
    [SCANNER_PUNCTUATION_TYPE_AND] = "AND",
    [SCANNER_PUNCTUATION_TYPE_BITWISE_OR] = "BITWISE_OR",
    [SCANNER_PUNCTUATION_TYPE_BITWISE_XOR] = "BITWISE_XOR",
    [SCANNER_PUNCTUATION_TYPE_BITWISE_SHIFT_LEFT] = "BITWISE_SHIFT_LEFT",
    [SCANNER_PUNCTUATION_TYPE_BITWISE_SHIFT_RIGHT] = "BITWISE_SHIFT_RIGHT",

    [SCANNER_PUNCTUATION_TYPE_DIRECT_ASSIGNMENT] = "DIRECT_ASSIGNMENT",
    [SCANNER_PUNCTUATION_TYPE_ADDITION_ASSIGNMENT] = "ADDITION_ASSIGNMENT",
    [SCANNER_PUNCTUATION_TYPE_SUBTRACTION_ASSIGNMENT] = "SUBTRACTION_ASSIGNMENT",
    [SCANNER_PUNCTUATION_TYPE_MULTIPLICATION_ASSIGNMENT] = "MULTIPLICATION_ASSIGNMENT",
    [SCANNER_PUNCTUATION_TYPE_DIVISION_ASSIGNMENT] = "DIVISION_ASSIGNMENT",
    [SCANNER_PUNCTUATION_TYPE_MODULO_ASSIGNMENT] = "MODULO_ASSIGNMENT",
    [SCANNER_PUNCTUATION_TYPE_BITWISE_AND_ASSIGNMENT] = "BITWISE_AND_ASSIGNMENT",
    [SCANNER_PUNCTUATION_TYPE_BITWISE_OR_ASSIGNMENT] = "BITWISE_OR_ASSIGNMENT",
    [SCANNER_PUNCTUATION_TYPE_BITWISE_XOR_ASSIGNMENT] = "BITWISE_XOR_ASSIGNMENT",
    [SCANNER_PUNCTUATION_TYPE_BITWISE_SHIFT_LEFT_ASSIGNMENT] = "BITWISE_SHIFT_LEFT_ASSIGNMENT",
    [SCANNER_PUNCTUATION_TYPE_BITWISE_SHIFT_RIGHT_ASSIGNMENT] = "BITWISE_SHIFT_RIGHT_ASSIGNMENT",

    [SCANNER_PUNCTUATION_TYPE_DEREFERENCE] = "DEREFERENCE",
    [SCANNER_PUNCTUATION_TYPE_POINTER_TO_DEREFERENCE] = "POINTER_TO_DEREFERENCE",
    [SCANNER_PUNCTUATION_TYPE_POINTER_TO_REFERENCE] = "POINTER_TO_REFERENCE",

    [SCANNER_PUNCTUATION_TYPE_CURLY_OPEN] = "CURLY_OPEN",
    [SCANNER_PUNCTUATION_TYPE_CURLY_CLOSE] = "CURLY_CLOSE",
    [SCANNER_PUNCTUATION_TYPE_SQUARE_OPEN] = "SQUARE_OPEN",
    [SCANNER_PUNCTUATION_TYPE_SQUARE_CLOSE] = "SQUARE_CLOSE",
    [SCANNER_PUNCTUATION_TYPE_PAREN_OPEN] = "PAREN_OPEN",
    [SCANNER_PUNCTUATION_TYPE_PAREN_CLOSE] = "PAREN_CLOSE",

    [SCANNER_PUNCTUATION_TYPE_SEMICOLON] = "SEMICOLON",
    [SCANNER_PUNCTUATION_TYPE_COLON] = "COLON",

    [SCANNER_PUNCTUATION_TYPE_ELLIPSIS] = "ELLIPSIS",
    [SCANNER_PUNCTUATION_TYPE_QUESTION_MARK] = "QUESTION_MARK",
    [SCANNER_PUNCTUATION_TYPE_PERIOD] = "PERIOD",
    [SCANNER_PUNCTUATION_TYPE_COMMA] = "COMMA",
};

void token_stringify(char * buffer, token_t * token) {
    switch (token->type) {
        case TOKEN_TYPE_KEYWORD: {
            token_data_keyword_t * data = token->data;

            strcpy(buffer, keyword_strings[data->keyword]);
        } break;

        case TOKEN_TYPE_IDENTIFIER: {
            token_data_identifier_t * data = token->data;

            sprintf(buffer, "ID(%s)", data->name);
        } break;

        case TOKEN_TYPE_CONSTANT: {
            token_data_constant_t * data = token->data;

            char * end = stpcpy(buffer, constant_strings[data->type]);
            switch (data->type) {
                case SCANNER_CONSTANT_TYPE_ULL:
                case SCANNER_CONSTANT_TYPE_UL:
                case SCANNER_CONSTANT_TYPE_UI:
                case SCANNER_CONSTANT_TYPE_US:
                case SCANNER_CONSTANT_TYPE_UC:
                case SCANNER_CONSTANT_TYPE_SLL:
                case SCANNER_CONSTANT_TYPE_SL:
                case SCANNER_CONSTANT_TYPE_SI:
                case SCANNER_CONSTANT_TYPE_SS:
                case SCANNER_CONSTANT_TYPE_SC: {
                    sprintf(end, "(%llu)", data->i);
                } break;

                case SCANNER_CONSTANT_TYPE_FLOAT: {
                    sprintf(end, "(%f)", data->f);
                } break;

                case SCANNER_CONSTANT_TYPE_DOUBLE: {
                    sprintf(end, "(%f)", data->d);
                } break;
            }
        } break;

        case TOKEN_TYPE_PUNCTUATION: {
            token_data_punctuation_t * data = token->data;

            strcpy(buffer, punctuation_strings[data->type]);
        } break;

        case TOKEN_TYPE_STRING_LITERAL: {
            token_data_string_literal_t * data = token->data;

            snprintf(
                buffer, TOKEN_STRINGIFY_BUFFER_REQUIREMENT,
                "\"%s\"",
                data->content
            );
        } break;

        default: strcpy(buffer, "ERROR"); break;
    }
}
