#pragma once

typedef enum {
    TOKEN_TYPE_IDENTIFIER,
    TOKEN_TYPE_KEYWORD,
    TOKEN_TYPE_CONSTANT,
    TOKEN_TYPE_PUNCTUATION,
    TOKEN_TYPE_STRING_LITERAL,
} token_type_t;

typedef struct {
    token_type_t type;
    size_t line, position;
    void * data;
} token_t;

typedef struct {
    char * name;
} token_data_identifier_t;

typedef enum {
    SCANNER_KEYWORD_TYPE_BREAK,
    SCANNER_KEYWORD_TYPE_CASE,
    SCANNER_KEYWORD_TYPE_CHAR,
    SCANNER_KEYWORD_TYPE_CONST,
    SCANNER_KEYWORD_TYPE_CONTINUE,
    SCANNER_KEYWORD_TYPE_DEFAULT,
    SCANNER_KEYWORD_TYPE_DO,
    SCANNER_KEYWORD_TYPE_DOUBLE,
    SCANNER_KEYWORD_TYPE_ELSE,
    SCANNER_KEYWORD_TYPE_ENUM,
    SCANNER_KEYWORD_TYPE_EXTERN,
    SCANNER_KEYWORD_TYPE_FLOAT,
    SCANNER_KEYWORD_TYPE_FOR,
    SCANNER_KEYWORD_TYPE_GOTO,
    SCANNER_KEYWORD_TYPE_IF,
    SCANNER_KEYWORD_TYPE_INLINE,
    SCANNER_KEYWORD_TYPE_INT,
    SCANNER_KEYWORD_TYPE_LONG,
    SCANNER_KEYWORD_TYPE_REGISTER,
    SCANNER_KEYWORD_TYPE_RESTRICT,
    SCANNER_KEYWORD_TYPE_RETURN,
    SCANNER_KEYWORD_TYPE_SHORT,
    SCANNER_KEYWORD_TYPE_SIGNED,
    SCANNER_KEYWORD_TYPE_SIZEOF,
    SCANNER_KEYWORD_TYPE_STATIC,
    SCANNER_KEYWORD_TYPE_STRUCT,
    SCANNER_KEYWORD_TYPE_SWITCH,
    SCANNER_KEYWORD_TYPE_TYPEDEF,
    SCANNER_KEYWORD_TYPE_UNION,
    SCANNER_KEYWORD_TYPE_UNSIGNED,
    SCANNER_KEYWORD_TYPE_VOID,
    SCANNER_KEYWORD_TYPE_VOLATILE,
    SCANNER_KEYWORD_TYPE_WHILE,
    SCANNER_KEYWORD_TYPE_BOOL,
    SCANNER_KEYWORD_TYPE_COMPLEX,
    SCANNER_KEYWORD_TYPE_IMAGINARY,
} token_data_keyword_type_t;
typedef struct {
    token_data_keyword_type_t keyword;
} token_data_keyword_t;

typedef enum {
    SCANNER_CONSTANT_TYPE_UC,
    SCANNER_CONSTANT_TYPE_US,
    SCANNER_CONSTANT_TYPE_UI,
    SCANNER_CONSTANT_TYPE_UL,
    SCANNER_CONSTANT_TYPE_ULL,

    SCANNER_CONSTANT_TYPE_SC,
    SCANNER_CONSTANT_TYPE_SS,
    SCANNER_CONSTANT_TYPE_SI,
    SCANNER_CONSTANT_TYPE_SL,
    SCANNER_CONSTANT_TYPE_SLL,

    SCANNER_CONSTANT_TYPE_FLOAT,
    SCANNER_CONSTANT_TYPE_DOUBLE,
} token_data_constant_type_t;
typedef struct {
    token_data_constant_type_t type;
    union {
        unsigned long long u;
        signed long long s;
        float f;
        float d;
    };
} token_data_constant_t;

typedef enum {
    SCANNER_PUNCTUATION_TYPE_PLUS,
    SCANNER_PUNCTUATION_TYPE_MINUS,
    SCANNER_PUNCTUATION_TYPE_STAR,
    SCANNER_PUNCTUATION_TYPE_SLASH,
    SCANNER_PUNCTUATION_TYPE_PERCENT,
    SCANNER_PUNCTUATION_TYPE_INCREMENT,
    SCANNER_PUNCTUATION_TYPE_DECREMENT,

    SCANNER_PUNCTUATION_TYPE_EQUAL_TO,
    SCANNER_PUNCTUATION_TYPE_NOT_EQUAL_TO,
    SCANNER_PUNCTUATION_TYPE_GREATER_THAN,
    SCANNER_PUNCTUATION_TYPE_LESS_THAN,
    SCANNER_PUNCTUATION_TYPE_GREATER_THAN_OR_EQUAL_TO,
    SCANNER_PUNCTUATION_TYPE_LESS_THAN_OR_EQUAL_TO,

    SCANNER_PUNCTUATION_TYPE_LOGICAL_NEGATION,
    SCANNER_PUNCTUATION_TYPE_LOGICAL_AND,
    SCANNER_PUNCTUATION_TYPE_LOGICAL_OR,

    SCANNER_PUNCTUATION_TYPE_BITWISE_NOT,
    SCANNER_PUNCTUATION_TYPE_AND,
    SCANNER_PUNCTUATION_TYPE_BITWISE_OR,
    SCANNER_PUNCTUATION_TYPE_BITWISE_XOR,
    SCANNER_PUNCTUATION_TYPE_BITWISE_SHIFT_LEFT,
    SCANNER_PUNCTUATION_TYPE_BITWISE_SHIFT_RIGHT,

    SCANNER_PUNCTUATION_TYPE_DIRECT_ASSIGNMENT,
    SCANNER_PUNCTUATION_TYPE_ADDITION_ASSIGNMENT,
    SCANNER_PUNCTUATION_TYPE_SUBTRACTION_ASSIGNMENT,
    SCANNER_PUNCTUATION_TYPE_MULTIPLICATION_ASSIGNMENT,
    SCANNER_PUNCTUATION_TYPE_DIVISION_ASSIGNMENT,
    SCANNER_PUNCTUATION_TYPE_MODULO_ASSIGNMENT,
    SCANNER_PUNCTUATION_TYPE_BITWISE_AND_ASSIGNMENT,
    SCANNER_PUNCTUATION_TYPE_BITWISE_OR_ASSIGNMENT,
    SCANNER_PUNCTUATION_TYPE_BITWISE_XOR_ASSIGNMENT,
    SCANNER_PUNCTUATION_TYPE_BITWISE_SHIFT_LEFT_ASSIGNMENT,
    SCANNER_PUNCTUATION_TYPE_BITWISE_SHIFT_RIGHT_ASSIGNMENT,

    SCANNER_PUNCTUATION_TYPE_DEREFERENCE,
    SCANNER_PUNCTUATION_TYPE_POINTER_TO_DEREFERENCE,
    SCANNER_PUNCTUATION_TYPE_POINTER_TO_REFERENCE,
    
    SCANNER_PUNCTUATION_TYPE_CURLY_OPEN,
    SCANNER_PUNCTUATION_TYPE_CURLY_CLOSE,
    SCANNER_PUNCTUATION_TYPE_SQUARE_OPEN,
    SCANNER_PUNCTUATION_TYPE_SQUARE_CLOSE,
    SCANNER_PUNCTUATION_TYPE_PAREN_OPEN,
    SCANNER_PUNCTUATION_TYPE_PAREN_CLOSE,

    SCANNER_PUNCTUATION_TYPE_SEMICOLON,

    SCANNER_PUNCTUATION_TYPE_ELLIPSIS,
    SCANNER_PUNCTUATION_TYPE_QUESTION_MARK,
    SCANNER_PUNCTUATION_TYPE_PERIOD,
} token_data_punctuation_type_t;
typedef struct {
    token_data_punctuation_type_t type;
} token_data_punctuation_t;

typedef struct {
    char * content;
} token_data_string_literal_t;

void token_init(token_t * token, token_type_t type);
void token_free(token_t * token);